#
# Deploy premium and standard storage classes for Azure
#

# ------------------- StorageClass ------------------- #

kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: azure-premium
  labels:
    kubernetes.io/cluster-service: "true"
provisioner: kubernetes.io/azure-disk
allowVolumeExpansion: true
parameters:
    storageaccounttype: Premium_LRS
    kind: managed
reclaimPolicy: Delete

---

kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: azure-standard
  labels:
    kubernetes.io/cluster-service: "true"
provisioner: kubernetes.io/azure-disk
allowVolumeExpansion: true
parameters:
    storageaccounttype: Standard_LRS
    kind: managed
reclaimPolicy: Delete
