#
# Deploy the KeyVault-FlexVol example deployment in Kubernetes
#

# ------------------- Scaling Policy ------------------- #

apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: kv-example
  namespace: default
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: kv-example
  minReplicas: 1
  maxReplicas: 3
  metrics:
  - type: Resource
    resource:
      name: cpu
      targetAverageUtilization: 90

---

# ------------------- Deployment ------------------- #

kind: Deployment
apiVersion: apps/v1
metadata:
  name: kv-example
  namespace: default
  labels:
    app: kv-example
spec:
  replicas: 2
  selector:
    matchLabels:
      app: kv-example
  template:
    metadata:
      labels:
        app: kv-example
    spec:
      affinity:
            podAntiAffinity:
              preferredDuringSchedulingIgnoredDuringExecution:
              - weight: 1
                podAffinityTerm:
                  labelSelector:
                    matchExpressions:
                      - operator: In
                        key: app
                        values: 
                        - kv-example
                  topologyKey: kubernetes.io/hostname
      containers:
      - name: kv-example
        # !CHANGE THIS! To your real image reference for the container 
        image: busybox
        ports:
        - containerPort: 80
        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 3
          periodSeconds: 20
        resources:
          requests:
            memory: "100M"
            cpu: "0.125"
        volumeMounts:
        - name: keyvault
          mountPath: /kvmnt
          readOnly: true
      volumes:
      - name: keyvault
        flexVolume:
          driver: "azure/kv"
          secretRef:
            name: kvcreds
          options:
            keyvaultname: "<Change_Me>"                 # the name of the KeyVault
            keyvaultobjectnames: secret1;cert1;secret2  # list of KeyVault object names (semi-colon separated)
            keyvaultobjecttypes: secret;cert;secret     # list of KeyVault object types: secret, key or cert (semi-colon separated)
            resourcegroup: "<Change_Me>"                # the resource group of the KeyVault
            subscriptionid: "<Change_Me>"               # the subscription ID of the KeyVault
            tenantid: "<Change_Me>"                     # the tenant ID of the KeyVault